---
title: "Multivariate data vis, Linear projections, and their application to local explanations of models"
subtitle: "MI2 DataLab"
author: "Nicholas Spyrison"
email: "nicholas.syrison@monash.edu"
date: "11 October 2021"
length: "45 minutes"
affiliation: "Monash University"
repo: "nspyrison/mi2_talk"
output:
  xaringan::moon_reader:
    css:
      - ninjutsu
      - "assets/font-awesome-all.css"
      #- "assets/xaringan-themer.css"
      - "assets/tachyons-addon.css"
      - "assets/animate.css"
      - "assets/fira-code.css"
      - "assets/boxes.css"
      - "assets/table.css"
      - "assets/styles.css"
      - "assets/monash-brand.css"
      - "assets/monash-fonts.css"
      - "assets/slide-types.css"
      - "assets/custom.css"
    self_contained: false
    seal: false
    nature:
      highlightStyle: magula
      highlightLanguage: r
      highlightLines: true
      highlightSpans: false
      countIncrementalSlides: false
      slideNumberFormat: '%current%/%total%'
      navigation:
        scroll: false
        touch: true
        click: false
      ratio: '16:9'
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  eval      = TRUE,   # R code
  echo      = FALSE,  # code text
  include   = TRUE,   # plots
  fig.align = "center",
  collapse  = TRUE,
  message   = F, warning = F, error = F,
  cache     = F, cache.lazy = F
)
require("knitr")
require("kableExtra")
require("magrittr")
## for cheem stuff:
require("plotly")
require("spinifex")
require("tourr")
require("cheem")
```

# cut out everything, doesn't work...

have tried changing reulst knitr chunk opts...

set up gh-pages

TOP___
```{r echo=F, out.width='10%'}
X_std <- tourr::flea[,1:6] %>% spinifex::scale_sd()
clas <- tourr::flea$species
gt_path <- spinifex::save_history(X_std, max_bases = 6)

ggt <- ggtour(gt_path, angle = .2) +
  proto_default(list(color = clas, shape = clas))
#ggt
#length(ggt)
#animate_gganimate(ggt)
animate_plotly(ggt)
```
BOTTOM____
